runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  DATABASE_URL: 'mysql://bbxakfu2g1p2:pscale_pw_UR6RmNy-mWvERZtgcZXuq9x_1ia1ZhDpb-fdc59x84U@79qerhgskwu5.us-east-4.psdb.cloud/bookkeeping-app?ssl={"rejectUnauthorized":true}'
  JWT_SECRET: ken12345

